[package]
name = "leptos_frontend"
version = "0.1.0"
edition = "2024"

[dependencies]
console_error_panic_hook = "0.1"
leptos = { version = "0.6", features = ["csr"] }
log = "0.4"
reqwasm = "0.5"
serde = { version = "1.0", features = ["derive"] }
wasm-bindgen = "0.2"
